## Take different sets of adjusted counts from decontX outputs and prepare to run eQTL in select clusters
cluster_info: "data/cluster_info_qc.tsv"
vcf: "data/fusion.filtered-vcf.maf0.05-hwe1e6.vcf.gz"
vcf_index: "data/fusion.filtered-vcf.maf0.05-hwe1e6.vcf.gz.tbi"
sample_info: "data/sample_level_covariates_rna.tsv"
rna_mtx_dir: ["data/rna-counts-matrices/", "-counts-matrices"]
gene_info: "data/gencode.v30.gene_lengths.tsv"
gene_types: ["protein_coding", "lincRNA", "3prime_overlapping_ncRNA", "antisense", "bidirectional_promoter_lncRNA", "macro_lncRNA", "non_coding", "sense_intronic", "sense_overlapping"]
exclude_chrs: ["chrM", "chrX", "chrY"]
n_pheno_pcs: [5, 10, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80, 100]
n_geno_pcs: [3]
other_covs: ['hqaa_umi_median', 'fraction_mitochondrial_median', 'n_nuclei', 'age', 'sex', 'batch', 'bmi']
permutations: 1000
window: 250000
cis_window: 1000000
total_chunks: 30